version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgres/data
  backend:
    image: kom1969/kittygram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
  frontend:
    env_file: .env
    image: kom1969/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static
  gateway:
    image: kom1969/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/